### ISSUE TITLE
How to sort out translation issues?

### ISSUE THREAD

**Issue by railization** [codevise/pageflow-external-links#14]
Hi Pageflow team,

I am currently experiencing translation issues. Could you help?

Thanks...

**Comment by kioopi** [comment]
For simple sentences [Google Translate](https://translate.google.com/) does an amazing job. They even have an app.

But seriously, you'd have to provide more information about your issue if you want someone to be able to help you.

**Comment by railization** [comment]
[missing "en.pageflow.external_links.manage_sites" translation] 
The issue is that I have added external-links gem and i experience this translation issue , I resolved the issue on local machine by removing sprocket folder as mentioned in troubleshooting but I am unable to resolve this by doing so on server. My server is running in development.

**Comment by kioopi** [comment]
Have you restarted the dev-server?

You may be able to force a reloading of you locales by doing `I18n.backend.reload!` in a rails console.

**Comment by railization** [comment]
Yes I did restart server however let me try the other solution too and get back to you if it doesn't work.

**Comment by railization** [comment]
This does not solves the issue.

**Comment by tf** [comment]
There are a couple of things you can try, to diagnose the error. 

1. On your production machine start a console session (i.e. `bundle exec rails console`) and try to access the missing translation there: `I18n.t('pageflow.external_links.manage_sites')`. I suspect this will work, since you were able to see translations on your local machine, which should not be the case if this was a more general dependency problem.

2. So translations are only missing in the editor, when they are accessed from JavaScript. During asset compilation all translations are written to the `pageflow/application.js` file. So if you are using asset precompilation, make sure you use up to date precompiled assets and assets compile without error. Make sure you reset all caches (sprockets tmp dir, browser cache).

**Comment by railization** [comment]
Thanks alot. Issue has been resolved. :)

**Comment by tf** [comment]
Just out of curiosity: What caused the issue?
